### PR TITLE
Clustering refactorings

### PR DESCRIPTION
**Pull request by whoisjones**
Hi @OatsProduction,

I checked your PR - what about reusing sklearn's clustering models? I wrote an initial wrapper class `ClusteringModel` that calls `sklearn.cluster`'s `fit()', `predict()` methods and so on. This way we can ensure the high quality of sklearn's implementations and integrate clustering functionality with flair and its datasets. What do you think?

### CODE REVIEW

**Comment by OatsProduction** [comment]
This is a good idea. Also these implementations are way less likely to have bugs...

As a work for my Study Project, I've implemented these algorithms from scratch. If it's okay for Alan, than I could use the sklearn implementation.

**Comment by alanakbik** [comment]
@OatsProduction yes you can use the sklearn implementation!

**Comment by OatsProduction** [comment]
This makes this sooo much easier. I will add the sklearn implementation.

**Comment by whoisjones** [comment]
@OatsProduction cool, can you merge this into master? then I could support you If you want

**Pull request merged**
